language: ruby
env:
  global:
    - secure: "eXNc/NbLIdZCBBfX39nZLanEoLpZcWdP61OmrMepP7HFARIaGQ5Mciu7c02GLIIwJsiut2ysD60DpbaK4DH5qbZy+hiMHaTog7jebN/8ou+5a8xMhB1IGOLIogC8RjYXBwSVEbQ3j+kkHRdlDMKA/qQkjnJyTnAKZ6H+48UVvIDufUJPycH+LpPYv4rBQrhbB2+rATBGJl10KMJxduF25rxUGLFOKlrax83irRKrwNG7roaS4GsDSrEjaBjzoL/9hH0jQFj5IcjVhNtpLNyrVolRbHC7PKDu4ksJi9wYMIwLWiRrqAkVPdCIy3mXaH+WiIkfYVy04CfrdegFEv+uB36IF4Fj5+QK/zhADzGpvGHq1J0IAlg5NGZHnlA14b7jA1V8COn95uV0T4Jo4YRqPbCKpAAeGM8StDbA4gCSok/UKkOFBBpvLjbik/31PXDZFRL2qkarMj45btERwXNfZ6X1n4cQ4QbbDo7DIEoAOjgaRwEkHvrRs/XIbcgao66phXUTGnVCnt0Hy0R5WFSk5bALJjaLb/ovBZVb39u/E8dURtIhDhfFfrfncNvq44DImJy8MMRt7jHk3PhSLbtMmfKB517r+PtXSts4e+wFXbQHleEItyTZa2jrDtBPtk6QlQUdiZEFLZHS1O42fMgmR04bNWsBw1xR5VKmxXnkeDU="
rvm:
  - 2.3.0
before_install:
  - gem install bundler -v 1.10.6
